### PR TITLE
Safari fix

### PR DESCRIPTION
**Pull request by 1auralynn**
e.buttons was returning undefined on safari

### CODE REVIEW

**Comment by 1auralynn** [comment]
Also added a removeEventListener to prevent drop events from multiplying.

**Comment by benj3** [comment]
I do get a setState Warning on this when removing an element from a app which doesn't happen with the original here @1auralynn might be something to do with an onClick event handler as it happens on every click.

**Comment by 1auralynn** [comment]
Hmm, not sure what that's about. If you paste the full warning in I might be able to figure out what's going on. I'm not getting the warning.

**Comment by benj3** [comment]
Not at the computer at the moment but it was a warning cannot set state on a unmounted object so something isn't being unmounted upon removal

**Pull request merged**
